//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public long Id { get; set; }
        public Nullable<int> glucose { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> userid { get; set; }
    
        public virtual users user { get; set; }
    }
}
