//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.data = new HashSet<data>();
        }
    
        public long Id { get; set; }
        public string Userid { get; set; }
    
        public virtual ICollection<data> data { get; set; }
    }
}
